missing_values_strategy: drop
on_error: raise
schema:
  ADAUSDT_funding_rate:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  ADAUSDT_price:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  BNBUSDT_funding_rate:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  BNBUSDT_price:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  BTCUSDT_funding_rate:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  BTCUSDT_price:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  ETHUSDT_funding_rate:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  ETHUSDT_price:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  SOLUSDT_funding_rate:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  SOLUSDT_price:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  XRPUSDT_funding_rate:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  XRPUSDT_price:
    dtype: float64
    max: 1000000
    min: 0
    on_error: warn
    required: true
  timestamp:
    dtype: datetime64[ns]
    on_error: raise
    required: true
