name: mlops_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - matplotlib
      - seaborn
      - pyyaml
      - pytest
      - pytest-cov
      # - xprocess
      - imbalanced-learn
      - requests


